# Pre-commit hooks for fraud detection model project
# Install: pip install pre-commit && pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # Black - Python code formatter
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3
        args: ['--config=pyproject.toml']

  # TODO: Enable validation hooks in next commit
  # # Check for trailing whitespace, end of file, etc.
  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: v4.5.0
  #   hooks:
  #     - id: trailing-whitespace
  #     - id: end-of-file-fixer
  #     - id: check-yaml
  #     - id: check-added-large-files
  #       args: ['--maxkb=1000']
  #     - id: check-json
  #     - id: check-merge-conflict
  #     - id: check-toml
  #     - id: debug-statements
  #     - id: mixed-line-ending
  #       args: ['--fix=lf']

  # isort - Sort imports (configured to work with Black)
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ['--profile=black', '--line-length=88']

  # Ruff - Fast Python linter with auto-fix (linting only, Black handles formatting)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.3
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  # TODO: Enable in next commit
  # # Flake8 - Python linting (optional, complements Black)
  # - repo: https://github.com/PyCQA/flake8
  #   rev: 7.0.0
  #   hooks:
  #     - id: flake8
  #       args: [
  #         '--max-line-length=88',  # Match Black's line length
  #         '--extend-ignore=E203,W503',  # Ignore conflicts with Black
  #         '--exclude=.git,__pycache__,docs/,build,dist,*.egg,data/,models/'
  #       ]

  # TODO: Enable in next commit
  # # mypy - Static type checking (optional)
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.8.0
  #   hooks:
  #     - id: mypy
  #       args: ['--ignore-missing-imports', '--no-strict-optional']
  #       additional_dependencies: [types-requests, types-PyYAML]
  #       exclude: ^(docs/|scripts/|tests/)

# Configuration for ci
ci:
  autoupdate_schedule: weekly
  skip: [mypy]  # Skip mypy in CI if it's too strict
  submodules: false
