# AlertManager configuration for GitOps alerts
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-gitops-config
  namespace: monitoring
  labels:
    app: alertmanager
    component: gitops-config
data:
  gitops-routes.yml: |
    # GitOps-specific routing rules
    global:
      smtp_smarthost: 'mailserver.mlops.local:587'
      smtp_from: 'alerts@mlops.local'
      slack_api_url: 'https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX'

    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'gitops-default'
      routes:
        - match:
            severity: critical
          receiver: 'gitops-critical'
          routes:
            - match:
                alertname: GitOpsPipelineDown
              receiver: 'gitops-emergency'
        - match:
            component: argocd
          receiver: 'argocd-team'
        - match:
            component: argo-workflows
          receiver: 'ml-platform-team'

    receivers:
      - name: 'gitops-default'
        slack_configs:
        - channel: '#gitops-alerts'
          title: 'GitOps Alert: {{ .GroupLabels.alertname }}'
          text: '{{ .CommonAnnotations.summary }}'

      - name: 'gitops-critical'
        slack_configs:
        - channel: '#gitops-critical'
          title: '🚨 CRITICAL GitOps Alert: {{ .GroupLabels.alertname }}'
          text: '{{ .CommonAnnotations.summary }}\n{{ .CommonAnnotations.description }}'
        email_configs:
        - to: 'oncall@mlops.local'
          subject: 'CRITICAL GitOps Alert'
          body: |
            Alert: {{ .GroupLabels.alertname }}
            Description: {{ .CommonAnnotations.description }}
            Runbook: {{ .CommonAnnotations.runbook_url }}

      - name: 'gitops-emergency'
        pagerduty_configs:
        - routing_key: 'YOUR_PAGERDUTY_KEY_HERE'
          description: 'GitOps Emergency: {{ .GroupLabels.alertname }}'
        slack_configs:
        - channel: '#gitops-emergency'
          title: '🔥 EMERGENCY GitOps Alert: {{ .GroupLabels.alertname }}'
          text: '{{ .CommonAnnotations.summary }}\nAction: {{ .CommonAnnotations.escalation }}'
        email_configs:
        - to: 'emergency@mlops.local'
          subject: 'EMERGENCY GitOps System Alert'

      - name: 'argocd-team'
        slack_configs:
        - channel: '#argocd-alerts'
          title: 'ArgoCD Alert: {{ .GroupLabels.alertname }}'

      - name: 'ml-platform-team'
        slack_configs:
        - channel: '#ml-platform-alerts'
          title: 'Argo Workflows Alert: {{ .GroupLabels.alertname }}'

    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'cluster', 'service']
