---
# Persistent Volume Claim for storing raw fraud detection data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fraud-raw-data-pvc
  namespace: fraud-detection
  labels:
    app.kubernetes.io/name: fraud-detection
    app.kubernetes.io/part-of: fraud-detection-system
    app.kubernetes.io/component: data-storage
spec:
  accessModes:
    - ReadWriteMany  # Multiple pods can read/write
  resources:
    requests:
      storage: 5Gi  # For raw Kaggle dataset
  storageClassName: nfs-shared  # Use existing NFS storage class
---
# Persistent Volume Claim for enriched fraud data and splits
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fraud-enriched-data-pvc
  namespace: fraud-detection
  labels:
    app.kubernetes.io/name: fraud-detection
    app.kubernetes.io/part-of: fraud-detection-system
    app.kubernetes.io/component: feature-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi  # For enriched dataset and train/test splits
  storageClassName: nfs-shared
---
# Persistent Volume Claim for trained fraud detection models
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fraud-models-pvc
  namespace: fraud-detection
  labels:
    app.kubernetes.io/name: fraud-detection
    app.kubernetes.io/part-of: fraud-detection-system
    app.kubernetes.io/component: model-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi  # For fraud_v1.keras and fraud_v2.keras models
  storageClassName: nfs-shared
