apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: fraud-data-pipeline-template
  namespace: fraud-detection
spec:
  entrypoint: data-ingestion-and-feature-engineering
  serviceAccountName: argo-workflow-sa
  
  # Global resource defaults for all containers
  podGC:
    strategy: OnPodSuccess
  
  # Resource requirements for Argo system containers
  podSpecPatch: |
    initContainers:
    - name: init
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi
    containers:
    - name: wait
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi
    - name: main
      resources:
        requests:
          cpu: 1
          memory: 2Gi
        limits:
          cpu: 2
          memory: 4Gi
  
  volumes:
  - name: fraud-raw-data-pvc
    persistentVolumeClaim:
      claimName: fraud-raw-data-pvc  # PVC for raw Kaggle data
  - name: fraud-enriched-data-pvc
    persistentVolumeClaim:
      claimName: fraud-enriched-data-pvc  # PVC for enriched/processed data

  templates:
  - name: data-ingestion-and-feature-engineering
    dag:
      tasks:
      - name: download-kaggle-data
        template: download-fraud-dataset
      - name: enrich-data
        dependencies: [download-kaggle-data]
        template: enrich-and-split-data

  - name: download-fraud-dataset
    container:
      image: harbor.test/library/fraud-detector:latest
      command: ["python", "src/download.py"]
      envFrom:
        - secretRef:
            name: ml-platform
      env:
      - name: LOGLEVEL
        value: "INFO"
      - name: DATA_DIR
        value: "/mnt/fraud-data/raw"
      - name: KAGGLE_USERNAME
        valueFrom:
          secretKeyRef:
            name: kaggle-credentials
            key: username
      - name: KAGGLE_KEY
        valueFrom:
          secretKeyRef:
            name: kaggle-credentials
            key: key
      volumeMounts:
        - name: fraud-raw-data-pvc
          mountPath: /mnt/fraud-data
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "1"
      securityContext:
        runAsNonRoot: false
        runAsUser: 0

  - name: enrich-and-split-data
    container:
      image: harbor.test/library/fraud-detector:latest
      command: ["python", "src/data.py"]
      envFrom:
        - secretRef:
            name: ml-platform
      env:
      - name: MLFLOW_TRACKING_URI
        value: "http://mlflow.mlflow.svc.cluster.local:5000"
      - name: DATA_DIR
        value: "/mnt/fraud-data"
      - name: ENRICHED_DIR
        value: "/mnt/fraud-enriched/enriched"
      - name: SPLITS_DIR
        value: "/mnt/fraud-enriched/splits"
      - name: TARGET_ROWS
        value: "1000000"
      - name: FRAUD_RATE
        value: "0.01"
      volumeMounts:
        - name: fraud-raw-data-pvc
          mountPath: /mnt/fraud-data
        - name: fraud-enriched-data-pvc
          mountPath: /mnt/fraud-enriched
      resources:
        requests:
          memory: "2Gi"
          cpu: "1"
        limits:
          memory: "4Gi"
          cpu: "2"
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
  
  # imagePullSecrets:
  # - name: ghcr
