apiVersion: mlops.seldon.io/v1alpha1
kind: Server
metadata:
  name: mlserver
  namespace: fraud-detection
  labels:
    app.kubernetes.io/name: fraud-detection
    app.kubernetes.io/part-of: fraud-detection-system
    app.kubernetes.io/managed-by: kustomize
spec:
  serverConfig: mlserver-config  # Pattern 3: References ServerConfig in seldon-system namespace
  capabilities: ["mlserver", "alibi-detect", "alibi-explain", "huggingface", "lightgbm", "mlflow", "python", "sklearn", "spark-mlib", "xgboost", "torch", "numpy"]
  replicas: 1