apiVersion: mlops.seldon.io/v1alpha1
kind: Server
metadata:
  name: mlserver
  namespace: fraud-detection
  labels:
    app.kubernetes.io/name: fraud-detection
    app.kubernetes.io/part-of: fraud-detection-system
    app.kubernetes.io/managed-by: kustomize
spec:
  serverConfig: mlserver-config  # References local ServerConfig in fraud-detection namespace
  capabilities: ["mlserver", "mlflow", "sklearn"]
  replicas: 1
