apiVersion: v1
kind: ConfigMap
metadata:
  name: fraud-detection-prometheus
  namespace: fraud-detection
data:
  prometheus.yml: |
    {
        "global": {
            "scrape_interval": "15s",
            "evaluation_interval": "15s"
        },
        "scrape_configs": [
            {
                "job_name": "seldon-scheduler",
                "static_configs": [
                    {
                        "targets": [
                            "seldon-scheduler.seldon-system.svc.cluster.local:9006"
                        ]
                    }
                ],
                "metrics_path": "/metrics",
                "scrape_interval": "10s"
            },
            {
                "job_name": "seldon-models",
                "kubernetes_sd_configs": [
                    {
                        "role": "service",
                        "namespaces": {
                            "names": [
                                "fraud-detection"
                            ]
                        }
                    }
                ],
                "relabel_configs": [
                    {
                        "source_labels": [
                            "__meta_kubernetes_service_annotation_prometheus_io_scrape"
                        ],
                        "action": "keep",
                        "regex": true
                    }
                ]
            }
        ],
        "rule_files": [
            "fraud_detection_alerts.yml"
        ]
    }
