---
apiVersion: mlops.seldon.io/v1alpha1
kind: SeldonRuntime
metadata:
  name: fraud-mlops-runtime
  namespace: fraud-detection
  labels:
    app.kubernetes.io/name: fraud-detection
    app.kubernetes.io/part-of: fraud-detection-system
    app.kubernetes.io/managed-by: kustomize
spec:
  config:
    agentConfig:
      rclone:
        config_secrets:
        - seldon-rclone-gs-public
    kafkaConfig: {}
    serviceConfig: {}
    tracingConfig: {}
  overrides:
  # No scheduler override - use centralized scheduler from seldon-system
  - name: seldon-envoy
    replicas: 1
  - name: seldon-dataflow-engine
    replicas: 0
  - name: seldon-modelgateway
    replicas: 1
  - name: seldon-pipelinegateway
    replicas: 0
  - name: mlserver
    replicas: 1
  seldonConfig: default