---
apiVersion: mlops.seldon.io/v1alpha1
kind: SeldonRuntime
metadata:
  name: fraud-mlops-runtime
  namespace: seldon-system
  labels:
    app.kubernetes.io/name: fraud-detection
    app.kubernetes.io/part-of: ml-platform
    app.kubernetes.io/managed-by: kustomize
spec:
  config:
    agentConfig:
      rclone:
        config_secrets:
        - seldon-rclone-gs-public
        - ml-platform
    kafkaConfig: {}
    serviceConfig: {}
    tracingConfig: {}
  overrides:
  - name: hodometer
    replicas: 1
  - name: seldon-scheduler
    replicas: 1
    podSpec:
      containers:
      - name: scheduler
        image: harbor.test/library/seldon-scheduler:2.9.1
        imagePullPolicy: Always
  - name: seldon-envoy
    replicas: 1
  - name: seldon-dataflow-engine
    replicas: 0
  - name: seldon-modelgateway
    replicas: 1
  - name: seldon-pipelinegateway
    replicas: 0
  - name: mlserver
    replicas: 1
  seldonConfig: default