---
# Pattern 3: This SeldonRuntime resource is NOT used in Pattern 3
# Instead, runtime components are deployed via Helm chart
# See runtime-pattern3.yaml for deployment instructions
#
# This file is kept for reference but should be excluded from kustomization.yaml
apiVersion: mlops.seldon.io/v1alpha1
kind: SeldonRuntime
metadata:
  name: fraud-mlops-runtime
  namespace: fraud-detection
  labels:
    app.kubernetes.io/name: fraud-detection
    app.kubernetes.io/part-of: fraud-detection-system
    app.kubernetes.io/managed-by: kustomize
spec:
  config:
    agentConfig:
      rclone:
        config_secrets:
        - seldon-rclone-gs-public
    kafkaConfig: {}
    serviceConfig: {}
    tracingConfig: {}
  overrides:
  - name: seldon-scheduler
    replicas: 1  # Pattern 3: Each namespace has its own scheduler
  - name: seldon-envoy
    replicas: 1
  - name: seldon-dataflow-engine
    replicas: 0
  - name: seldon-modelgateway
    replicas: 1
  - name: seldon-pipelinegateway
    replicas: 0
  scheduler:
    enabled: true  # Pattern 3: Scheduler enabled in each namespace
  seldonConfig: default
