apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: fraud-training-pipeline-template
  namespace: fraud-detection
spec:
  entrypoint: train-model
  serviceAccountName: argo-workflow-sa

  podSpecPatch: |
    initContainers:
    - name: init
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi
    containers:
    - name: wait
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi

  volumes:
  - name: fraud-enriched-data-pvc
    persistentVolumeClaim:
      claimName: fraud-enriched-data-pvc
  - name: fraud-models-pvc
    persistentVolumeClaim:
      claimName: fraud-models-pvc

  templates:
  - name: train-model
    inputs:
      parameters:
      - name: model-version
        value: v1  # Default to baseline model, can be v1 or v2
    dag:
      tasks:
      - name: train-fraud-model
        template: train-fraud-detector
        arguments:
          parameters:
          - name: model-version
            value: "{{inputs.parameters.model-version}}"

  - name: train-fraud-detector
    inputs:
      parameters:
      - name: model-version
    container:
      image: harbor.test/library/fraud-detector:latest
      command:
      - sh
      - -c
      - |
        if [ "{{inputs.parameters.model-version}}" = "v2" ]; then
          echo "Training candidate model v2..."
          python src/candidate.py
        else
          echo "Training baseline model v1..."
          python src/baseline.py
        fi
      env:
      - name: MODEL_VERSION
        value: "{{inputs.parameters.model-version}}"
      - name: MLFLOW_TRACKING_URI
        value: "http://mlflow.mlflow.svc.cluster.local:5000"
      - name: DATA_DIR
        value: "/mnt/fraud-enriched"
      - name: MODEL_DIR
        value: "/mnt/fraud-models"
      - name: EPOCHS
        value: "10"
      - name: BATCH_SIZE
        value: "64"
      - name: LEARNING_RATE
        value: "0.001"
      - name: LOGLEVEL
        value: "INFO"
      envFrom:
        - secretRef:
            name: ml-platform
      volumeMounts:
        - name: fraud-enriched-data-pvc
          mountPath: /mnt/fraud-enriched
        - name: fraud-models-pvc
          mountPath: /mnt/fraud-models
      resources:
        requests:
          memory: "2Gi"
          cpu: "1"
        limits:
          memory: "4Gi"
          cpu: "2"

  # imagePullSecrets:
  # - name: ghcr
