name: ML Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      model_version:
        description: 'Model version to train (e.g., v3)'
        required: false
        default: 'v2'

env:
  MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
  MLFLOW_S3_ENDPOINT_URL: ${{ secrets.MLFLOW_S3_ENDPOINT_URL }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  HARBOR_REGISTRY: ${{ secrets.HARBOR_REGISTRY }}
  HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
  HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}

jobs:
  data-validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy scikit-learn

    - name: Validate data
      run: |
        python -c "
        import pandas as pd
        import os

        # Check if enriched data exists
        if not os.path.exists('data/enriched/fraud_dataset.csv'):
            print('Enriched dataset not found. Running data preparation...')
            exit(1)

        # Load and validate
        df = pd.read_csv('data/enriched/fraud_dataset.csv')
        assert len(df) > 900000, f'Expected >900k rows, got {len(df)}'
        assert 'Class' in df.columns, 'Missing Class column'
        assert df['Class'].nunique() == 2, 'Class should be binary'

        print(f'✓ Data validation passed: {len(df)} rows, {df.shape[1]} columns')
        print(f'✓ Fraud rate: {df["Class"].mean():.2%}')
        "

  train-models:
    needs: data-validation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        model: [baseline, candidate]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tensorflow pandas numpy scikit-learn mlflow boto3

    - name: Train ${{ matrix.model }} model
      run: |
        MODEL_TYPE=${{ matrix.model }} python src/train_model.py

    - name: Upload model info
      uses: actions/upload-artifact@v3
      with:
        name: model-${{ matrix.model }}-info
        path: |
          models/fraud_*.keras
          models/*_model_uri.txt
          models/*_metrics.json

  test-models:
    needs: train-models
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tensorflow pandas numpy scikit-learn pytest

    - name: Download model artifacts
      uses: actions/download-artifact@v3
      with:
        path: models/

    - name: Run model tests
      run: |
        # Create test file
        cat > test_models.py << 'EOF'
        import tensorflow as tf
        import pandas as pd
        import numpy as np
        import json

        def test_model_loading():
            """Test that models can be loaded"""
            v1_model = tf.keras.models.load_model('models/model-baseline-info/fraud_v1.keras')
            v2_model = tf.keras.models.load_model('models/model-candidate-info/fraud_v2.keras')
            assert v1_model is not None
            assert v2_model is not None

        def test_model_prediction():
            """Test model predictions on sample data"""
            v1_model = tf.keras.models.load_model('models/model-baseline-info/fraud_v1.keras')

            # Create sample input (30 features)
            sample_input = np.random.randn(1, 30).astype(np.float32)

            # Get prediction
            prediction = v1_model.predict(sample_input)

            # Check output shape and range
            assert prediction.shape == (1, 1)
            assert 0 <= prediction[0][0] <= 1

        def test_model_metrics():
            """Test that metrics meet thresholds"""
            with open('models/model-candidate-info/v2_metrics.json', 'r') as f:
                metrics = json.load(f)

            # Candidate model should have good recall
            assert metrics['recall'] > 0.7, f"Recall too low: {metrics['recall']}"
            assert metrics['precision'] > 0.5, f"Precision too low: {metrics['precision']}"

        if __name__ == "__main__":
            test_model_loading()
            test_model_prediction()
            test_model_metrics()
            print("✓ All model tests passed!")
        EOF

        python test_models.py

  build-container:
    needs: test-models
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Download model artifacts
      uses: actions/download-artifact@v3
      with:
        path: models/

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Harbor
      uses: docker/login-action@v2
      with:
        registry: ${{ env.HARBOR_REGISTRY }}
        username: ${{ env.HARBOR_USERNAME }}
        password: ${{ env.HARBOR_PASSWORD }}

    - name: Build and push MLServer image
      run: |
        # Create Dockerfile for MLServer
        cat > Dockerfile << 'EOF'
        FROM seldonio/mlserver:1.3.5-slim

        # Copy models
        COPY models/model-baseline-info/fraud_v1.keras /mnt/models/fraud-v1/
        COPY models/model-candidate-info/fraud_v2.keras /mnt/models/fraud-v2/

        # Create model-settings.json for each model
        RUN echo '{"name": "fraud-v1", "implementation": "mlserver_tensorflow.TensorFlowModel", "parameters": {"uri": "/mnt/models/fraud-v1/"}}' > /mnt/models/fraud-v1/model-settings.json
        RUN echo '{"name": "fraud-v2", "implementation": "mlserver_tensorflow.TensorFlowModel", "parameters": {"uri": "/mnt/models/fraud-v2/"}}' > /mnt/models/fraud-v2/model-settings.json
        EOF

        # Build and push
        docker buildx build \
          --platform linux/amd64 \
          --tag ${{ env.HARBOR_REGISTRY }}/mlops/fraud-model:${{ github.sha }} \
          --tag ${{ env.HARBOR_REGISTRY }}/mlops/fraud-model:latest \
          --push .

  update-manifests:
    needs: build-container
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Download model artifacts
      uses: actions/download-artifact@v3
      with:
        path: models/

    - name: Update Kubernetes manifests
      run: |
        # Read S3 URIs from training outputs
        V1_URI=$(cat models/model-baseline-info/v1_model_uri.txt)
        V2_URI=$(cat models/model-candidate-info/v2_model_uri.txt)

        # Update model config
        python scripts/update-model-config.py \
          --v1-uri "$V1_URI" \
          --v2-uri "$V2_URI" \
          --baseline-weight 80 \
          --candidate-weight 20

        # Update image tag in kustomization
        cd k8s/base
        sed -i "s|newTag: .*|newTag: ${{ github.sha }}|" kustomization.yaml

    - name: Generate deployment artifacts
      run: |
        # Store deployment artifacts instead of committing back to trigger repo
        mkdir -p deployment-artifacts
        
        # Copy updated manifests to artifacts
        cp -r k8s/ deployment-artifacts/
        
        # Create deployment metadata
        cat > deployment-artifacts/deployment-info.json << EOF
        {
          "commit_sha": "${{ github.sha }}",
          "build_time": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
          "models": {
            "v1_uri": "$(cat models/model-baseline-info/v1_model_uri.txt)",
            "v2_uri": "$(cat models/model-candidate-info/v2_model_uri.txt)"
          },
          "images": {
            "fraud_model": "${{ env.HARBOR_REGISTRY }}/mlops/fraud-model:${{ github.sha }}"
          }
        }
        EOF
        
        echo "✅ Deployment artifacts generated (no commit loop)"

    - name: Upload deployment artifacts  
      uses: actions/upload-artifact@v3
      with:
        name: deployment-manifests-${{ github.sha }}
        path: deployment-artifacts/
        retention-days: 30

  deploy-staging:
    needs: update-manifests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: staging
    steps:
    - uses: actions/checkout@v3

    - name: Download deployment artifacts
      uses: actions/download-artifact@v3
      with:
        name: deployment-manifests-${{ github.sha }}
        path: deployment-artifacts/

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.28.0'

    # In a real setup, this would use OIDC or service account tokens
    - name: Configure kubectl (placeholder)
      run: |
        echo "🔧 In production, configure kubectl with:"
        echo "  - OIDC provider authentication"
        echo "  - Kubernetes service account tokens"
        echo "  - Cluster endpoint: \${{ secrets.STAGING_CLUSTER_ENDPOINT }}"

    - name: Validate manifests
      run: |
        echo "🧪 Validating Kubernetes manifests..."
        cd deployment-artifacts
        
        # Validate staging kustomization
        kubectl kustomize k8s/overlays/staging/ --dry-run=client
        echo "✅ Staging manifests are valid"

    - name: Deploy to staging (simulation)
      run: |
        echo "🚀 Simulated staging deployment:"
        echo "  kubectl apply -k deployment-artifacts/k8s/overlays/staging/"
        echo "  kubectl rollout status deployment/mlserver -n fraud-detection-staging"
        echo "  kubectl wait --for=condition=ready pod -l app=mlserver -n fraud-detection-staging --timeout=300s"

    - name: Run smoke tests
      run: |
        echo "🧪 Simulated smoke tests:"
        echo "  curl -X POST http://staging-fraud-detection/v2/models/fraud-v1-baseline/infer"
        echo "  curl -X POST http://staging-fraud-detection/v2/models/fraud-v2-candidate/infer"
        echo "✅ All smoke tests would pass"

    - name: Report deployment
      run: |
        echo "✅ Staging deployment complete!"
        
        # Read deployment metadata
        if [ -f deployment-artifacts/deployment-info.json ]; then
          echo "📊 Deployment details:"
          cat deployment-artifacts/deployment-info.json | jq '.'
        fi
        
        echo "🎯 Next: Manual approval for production deployment"
